added check for updated version available, added debug step

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,8 +11,6 @@ on:
     types:
     - opened
     - reopened
-  schedule:
-  - cron: "0 0 * * 6"
 
 jobs:
   build:
@@ -22,8 +20,58 @@ jobs:
     - name: Checkout
       uses: actions/checkout@v2
 
-    - name: Set build date
-      run: echo "BUILD_DATE=$(date '+%Y-%m-%dT%H:%M:%S%:z')" >> $GITHUB_ENV
+    - name: Check for newer version
+      if: github.ref == 'refs/heads/master'
+      run: |
+        echo "**** Retrieving external version ****"
+        EXT_RELEASE=$(curl -s https://api.github.com/repos/invoiceninja/invoiceninja/releases | jq -rc 'limit(1;.[] | select( .target_commitish | match("v5-stable"))) .tag_name')
+        if [ -z "${EXT_RELEASE}" ] || [ "${EXT_RELEASE}" == "null" ]; then
+          echo "**** Can't retrieve external version, exiting ****"
+          exit 1
+        fi
+
+        EXT_RELEASE=$(echo ${EXT_RELEASE} | sed 's/[~,%@+;:/]//g')
+
+        echo "**** External version: ${EXT_RELEASE} ****"
+
+        echo "**** Retrieving last pushed version ****"
+
+        image="linuxserver-labs/invoiceninja"
+        tag="latest"
+        token=$(curl -sX GET \
+          "https://ghcr.io/token?scope=repository%3Alinuxserver-labs%2Finvoiceninja%3Apull" \
+          | jq -r '.token')
+        multidigest=$(curl -s \
+          --header "Accept: application/vnd.docker.distribution.manifest.v2+json" \
+          --header "Authorization: Bearer ${token}" \
+          "https://ghcr.io/v2/${image}/manifests/${tag}" \
+          | jq -r 'first(.manifests[].digest)')
+        digest=$(curl -s \
+          --header "Accept: application/vnd.docker.distribution.manifest.v2+json" \
+          --header "Authorization: Bearer ${token}" \
+          "https://ghcr.io/v2/${image}/manifests/${multidigest}" \
+          | jq -r '.config.digest')
+        image_info=$(curl -sL \
+          --header "Authorization: Bearer ${token}" \
+          "https://ghcr.io/v2/${image}/blobs/${digest}" \
+          | jq -r '.config')
+
+        IMAGE_RELEASE=$(echo ${image_info} | jq -r '.Labels.build_version' | awk '{print $3}')
+        IMAGE_VERSION=$(echo ${IMAGE_RELEASE} | awk -F'-ls' '{print $1}')
+
+        if [ -z "${IMAGE_VERSION}" ]; then
+          echo "**** Can't retrieve last pushed version, exiting ****"
+          exit 1
+        fi
+
+        echo "**** Last pushed version: ${IMAGE_VERSION} ****"
+
+        if [ "${EXT_RELEASE}" == "${IMAGE_VERSION}" ]; then
+          echo "**** Version ${EXT_RELEASE} already pushed, exiting ****"
+          echo ::set-output name=update_available::false
+        fi
+
+        echo ::set-output name=update_available::true
 
     - name: Prepare
       id: prep
@@ -49,6 +97,10 @@ jobs:
         echo ::set-output name=github_server_url::"${GITHUB_SERVER_URL}"
         echo ::set-output name=BUILD_DATE::$(date '+%Y-%m-%dT%H:%M:%S%:z')
         echo ::set-output name=VERSION::${VERSION}
+
+    - name: Debug
+      run: |
+        echo ${{ github.even_name }}
 
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v1
